### PR TITLE
Our engineering culture contribution

### PR DESCRIPTION
**Pull request by LATaylor-guardian**

### CODE REVIEW

**Comment by rrees** [comment]
Looks good :+1:

**Comment by mchv** [comment]
:+1: I think this is really relevant

**Comment by davidfurey** [comment]
:+1:

**Comment by DiegoVazquezNanini** [comment]
:+1:

**Comment by rrees** [comment]
Whoops! I mis-counted the plus ones :blush: 

I'll revert if people feel strongly

**Comment by LATaylor-guardian** [comment]
:+1: Can't see anything about self voting! That makes five :)

**Comment by tackley** [comment]
Great!

**Pull request merged**
